# fly.toml app configuration file generated for passman-depl on 2025-01-18T09:33:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'passman-depl'
primary_region = 'yyz'

[build.args]
    PB_VERSION="0.24.4"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_services.concurrency]
    type = "requests"
    hard_limit = 500
    soft_limit = 550

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
    destination = "pb/pb_data"
    source = "pb_data"
